from io import BytesIO
from datetime import datetime

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from sqlalchemy import func
from sqlalchemy.orm import Session

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

from database import get_db
from dependencies import get_current_company, get_current_user
from models import (
    Company,
    User,
    Product,
    Inventory,
    ProductionOrder,
    SalesOrder,
    PurchaseOrder,
    WasteRecord,
    DowntimeRecord,
    QualityCheck,
)

router = APIRouter(prefix="/pdf-reports", tags=["PDF Reports"])


@router.get("/executive")
def download_executive_pdf(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
    company: Company = Depends(get_current_company),
):
    company_id = company.id

    products = db.query(Product).filter(Product.company_id == company_id).count()

    inventory_value = (
        db.query(func.sum(Inventory.quantity * Product.cost_price))
        .join(Product, Inventory.product_id == Product.id)
        .filter(Inventory.company_id == company_id)
        .scalar()
    ) or 0

    production_orders = (
        db.query(ProductionOrder)
        .filter(ProductionOrder.company_id == company_id)
        .count()
    )

    sales_value = (
        db.query(func.sum(SalesOrder.quantity * SalesOrder.unit_price))
        .filter(SalesOrder.company_id == company_id)
        .scalar()
    ) or 0

    purchase_value = (
        db.query(func.sum(PurchaseOrder.quantity * PurchaseOrder.unit_price))
        .filter(PurchaseOrder.company_id == company_id)
        .scalar()
    ) or 0

    waste_units = (
        db.query(func.sum(WasteRecord.quantity))
        .filter(WasteRecord.company_id == company_id)
        .scalar()
    ) or 0

    downtime_minutes = (
        db.query(func.sum(DowntimeRecord.duration_minutes))
        .filter(DowntimeRecord.company_id == company_id)
        .scalar()
    ) or 0

    quality_checks = (
        db.query(QualityCheck)
        .filter(QualityCheck.company_id == company_id)
        .count()
    )

    failed_checks = (
        db.query(QualityCheck)
        .filter(
            QualityCheck.company_id == company_id,
            QualityCheck.result == "Fail",
        )
        .count()
    )

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("SmartFactory AI - Executive Report", styles["Title"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph(f"Company: {company.name}", styles["Normal"]))
    story.append(Paragraph(f"Generated by: {current_user.full_name}", styles["Normal"]))
    story.append(Paragraph(f"Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", styles["Normal"]))
    story.append(Spacer(1, 20))

    data = [
        ["Metric", "Value"],
        ["Products", products],
        ["Inventory Value", f"EUR {round(inventory_value, 2)}"],
        ["Production Orders", production_orders],
        ["Sales Value", f"EUR {round(sales_value, 2)}"],
        ["Purchase Value", f"EUR {round(purchase_value, 2)}"],
        ["Waste Units", round(waste_units, 2)],
        ["Downtime Minutes", round(downtime_minutes, 2)],
        ["Quality Checks", quality_checks],
        ["Failed Quality Checks", failed_checks],
    ]

    table = Table(data, colWidths=[250, 220])

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E3A8A")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#F8FAFC")),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )

    story.append(table)
    story.append(Spacer(1, 20))

    story.append(Paragraph("Executive Summary", styles["Heading2"]))
    story.append(
        Paragraph(
            f"{company.name} currently has {products} products, "
            f"inventory value of EUR {round(inventory_value, 2)}, "
            f"sales value of EUR {round(sales_value, 2)}, and "
            f"{round(downtime_minutes, 2)} minutes of downtime.",
            styles["Normal"],
        )
    )

    doc.build(story)

    buffer.seek(0)

    filename = f"smartfactory_executive_report_{company.id}.pdf"

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f"attachment; filename={filename}"
        },
    )